c

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -33,7 +33,7 @@ commands:
                 npm install
                 npm run migrations:revert
             fi
-            
+
 jobs:
   build-frontend:
     docker:
@@ -60,11 +60,10 @@ jobs:
       - run:
           name: Back-end build
           command: |
-             cd backend && npm install && npm run build
+            cd backend && npm install && npm run build
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
-
   test-frontend:
     docker:
       - image: circleci/node:13.8.0
@@ -73,15 +72,13 @@ jobs:
       - restore_cache:
           keys: [frontend-build]
       - run:
-          name: Run front-end test
+          name: Test front-end
           command: |
-            cd frontend
-            npm install
-            npm run test
+            cd frontend && npm install && npm run test
       - save_cache:
           paths: [frontend/node_modules]
-          key: frontend-build            
-               
+          key: frontend-build
+                
   test-backend:
     docker:
       - image: circleci/node:13.8.0
@@ -90,50 +87,37 @@ jobs:
       - restore_cache:
           keys: [backend-build]
       - run:
-          name: Run Back-end test
+          name: Test back-end
           command: |
-            cd backend
-            npm install
-            npm run test
+            cd backend && npm install && npm run test
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
-            
   scan-frontend:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [frontend-build]
+          keys: [frontend-build] 
       - run:
-          name: Run front-end scan
+          name: Scan front-end
           command: |
-            cd frontend
-            npm install
-            # npm audit fix --audit-level=critical --force
-            # npm audit fix --force
-            npm audit fix --audit-level=critical
+            cd frontend && npm install && npm audit fix --audit-level=critical
       - save_cache:
           paths: [frontend/node_modules]
           key: frontend-build
-
   scan-backend:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [backend-build]
+          keys: [backend-build] 
       - run:
-          name: Run back-end scan
+          name: Scan back-end
           command: |
-            cd backend
-            npm install
-            # npm install oauth-sign@^0.9.0
-            # npm audit fix --audit-level=critical --force
-            # npm audit fix --force
-            npm audit fix --audit-level=critical
+            cd backend && npm install && npm audit fix --audit-level=critical
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
@@ -155,7 +139,7 @@ jobs:
               --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} \
               --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7} \
               --tags project=udapeople \
-              --region us-east-1
+              --region us-east-1 
       - run:
           name: Ensure front-end infrastructure exist
           command: |
@@ -177,7 +161,7 @@ jobs:
           paths:
             - "inventory.txt"
       - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}   
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
 
   configure-infrastructure:
     docker:
@@ -187,7 +171,7 @@ jobs:
       - add_ssh_keys:
           fingerprints: ["5d:f6:a8:fc:08:ac:a0:e7:af:d6:5a:47:e1:99:74:91"]
       - run:
-          name: Install dependencies
+          name: install ansible
           command: |
             pip install ansible
       - run:
@@ -200,20 +184,17 @@ jobs:
           name: Echo inventory
           command: cat ~/inventory.txt
       - run:
-          name: Configure server
-          command: |         
-            cd .circleci/ansible 
-            ansible-playbook -i ~/inventory.txt configure.yml
+          name: Run playbook and configure server
+          command: |
+            cd .circleci/ansible && ansible-playbook -i ~/inventory.txt main.yml
       - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7} 
-
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+    
   run-migrations:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
-      - restore_cache:
-          keys: [backend-build]    
       - attach_workspace:
           at: ~/
       - run:
@@ -223,17 +204,14 @@ jobs:
             npm install
             npm run migrations > migrations_dump.txt
       - run:
-          name: Send migration results to kvdb.io
+          name: Send migration status to kvdb.io
           command: |
             cd backend
-            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+            if grep -q "has been executed successfully."  migrations_dump.txt
             then
-              # If you are using memstash.io, generate the token "7933fe63-4687-4fa1-8426-aa25aa1730ec" on the website
-              curl -H "Content-Type: text/plain" -H "token: 7933fe63-4687-4fa1-8426-aa25aa1730ec" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
-              # If you are using kvdb.io, generate the bucket ID "9GE4jRtKznmVKRfvdBABBe" in your local terminal first
-              curl https://kvdb.io/9GE4jRtKznmVKRfvdBABBe/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+              curl --insecure https://kvdb.io/TFbubBBBgVe2hXFeyRNXtT/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
             fi
-    
+
   deploy-frontend:
     docker:
       - image: circleci/node:13.8.0
@@ -244,10 +222,7 @@ jobs:
       - run:
           name: Install tar utility
           command: |
-            apt-get update 
-            apt-get install python python-pip
-            pip install ansible
-            pip install awscli
+            sudo apt-get update && sudo apt-get install python python-pip
       - run:
           name: Install ansible and awscli
           command: |
@@ -271,19 +246,17 @@ jobs:
             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
 
       - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}          
-  
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+
   deploy-backend:
     docker:
       - image: python
     steps:
       - checkout
-      - restore_cache:
-          keys: [backend-build]       
       - add_ssh_keys:
           fingerprints: ["5d:f6:a8:fc:08:ac:a0:e7:af:d6:5a:47:e1:99:74:91"]
       - run:
-          name: Install dependencies
+          name: install requirement
           command: |
             pip install ansible
             pip install awscli
@@ -308,7 +281,6 @@ jobs:
           name: Deploy backend
           command: |
             cd backend
-            npm install typescript -g
             npm i
             npm run build
             cd ..
@@ -317,11 +289,11 @@ jobs:
             export BACKEND_IP=$(cat ~/inventory.txt)
             scp -r -o StrictHostKeyChecking=no artifact.tar.gz ubuntu@$BACKEND_IP:/home/ubuntu/
             cd .circleci/ansible
+            echo "Contents  of the ~/inventory.txt file is -------"
             cat ~/inventory.txt
             ansible-playbook -i ~/inventory.txt deploy-backend.yml
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-
   smoke-test:
     docker:
       - image: python
@@ -343,30 +315,31 @@ jobs:
           name: Backend smoke test.
           command: |
             export BACKEND_IP=$(cat ~/inventory.txt)
-            export API_URL="http://${BACKEND_IP}:3030"
+            export API_URL=http://$BACKEND_IP:3030
             echo $API_URL
             if curl "$API_URL/api/status" | grep "ok"
             then
-              exit 0
+                exit 0
             else
-              exit 1
+                exit 1
             fi
       - run:
           name: Frontend smoke test.
           command: |
             URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
             echo $URL
-            if curl -s ${URL} | grep "Welcome"
+            if curl -s $URL | grep "Welcome"
             then
+                # Change this to 0 after the job fails
               exit 0
             else
               exit 1
             fi
+            
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
       - revert-migrations:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}  
-
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
   cloudfront-update:
     docker:
       - image: amazon/aws-cli
@@ -396,7 +369,7 @@ jobs:
             --template-file .circleci/files/cloudfront.yml \
             --stack-name InitialStack \
             --parameter-overrides WorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7}" \
-            --tags project=udapeople    
+            --tags project=udapeople
   cleanup:
     docker:
       - image: amazon/aws-cli
@@ -425,7 +398,8 @@ jobs:
               aws cloudformation delete-stack --stack-name "udapeople-frontend-$OldID"
             else
               echo "Cannot cleanup resource"
-            fi            
+            fi
+
 
 workflows:
   deault:
